kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: "pv01"

