apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modresorts
  namespace: openshift-gitops
spec:
  destination:
    namespace: wlmod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/kustomize/overlays/dev 
    repoURL: https://github.com/barnsie007/bundle.git  
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

