apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maventest
spec:
  pipelineRef:
    name: maventest
  serviceAccountName: pipeline
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: build-workspace
      persistentVolumeClaim:
        claimName: maven
  params:
  - name: repo-url
    value: REPO-URL 
  - name: branch-name
    value: main
  - name: repo-dockerfile
    value: Containerfile
  - name: image-url
    value: IMAGE-URL
  - name: bundle
    value: BUNDLE 
  - name: branch
    value: imageupdate
  - name: deploymentfile
    value: DEPLOYMENTFILE 
  - name: user
    value: USER 
  - name: usermail
    value: MAIL 
  - name: userpassword
    value: PASSWORD
